package com.harsh.tournamentmanagerpro.controller;

import com.harsh.tournamentmanagerpro.entity.Role;
import com.harsh.tournamentmanagerpro.entity.User;
import com.harsh.tournamentmanagerpro.service.UserService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Arrays;
import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(UserController.class)
class UserControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private UserService userService;

    private User user;

    @BeforeEach
    void setUp() {
        user = new User();
        user.setUsername("testuser");
        user.setPassword("password");
        user.setRole(Role.OWNER);
    }

    // 1️⃣ POST /api/users/register — ADMIN only
    @Test
    @WithMockUser(roles = "ADMIN")
    void createUser_Admin_Success() throws Exception {
        when(userService.createUser(any())).thenAnswer(invocation -> {
            User u = invocation.getArgument(0);
            u.setId(1L); // simulate autogenerated ID
            return u;
        });

        mockMvc.perform(post("/api/users/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"username\":\"testuser\",\"password\":\"password\",\"role\":\"OWNER\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.username").value("testuser"))
                .andExpect(jsonPath("$.id").value(1));
    }

    @Test
    @WithMockUser(roles = "OWNER")
    void createUser_Owner_Forbidden() throws Exception {
        mockMvc.perform(post("/api/users/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"username\":\"testuser\",\"password\":\"password\",\"role\":\"OWNER\"}"))
                .andExpect(status().isForbidden());
    }

    // 2️⃣ GET /api/users — ADMIN only
    @Test
    @WithMockUser(roles = "ADMIN")
    void getAllUsers_Admin_Success() throws Exception {
        user.setId(1L);
        List<User> users = Arrays.asList(user);
        when(userService.getAllUsers()).thenReturn(users);

        mockMvc.perform(get("/api/users"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.size()").value(1))
                .andExpect(jsonPath("$[0].username").value("testuser"))
                .andExpect(jsonPath("$[0].id").value(1));
    }

    @Test
    @WithMockUser(roles = "OWNER")
    void getAllUsers_Owner_Forbidden() throws Exception {
        mockMvc.perform(get("/api/users"))
                .andExpect(status().isForbidden());
    }

    // 3️⃣ DELETE /api/users/{id} — ADMIN only
    @Test
    @WithMockUser(roles = "ADMIN")
    void deleteUser_Admin_Success() throws Exception {
        mockMvc.perform(delete("/api/users/1"))
                .andExpect(status().isNoContent());
        Mockito.verify(userService).deleteUser(1L);
    }

    @Test
    @WithMockUser(roles = "OWNER")
    void deleteUser_Owner_Forbidden() throws Exception {
        mockMvc.perform(delete("/api/users/1"))
                .andExpect(status().isForbidden());
    }

    // 4️⃣ GET /api/users/me — any authenticated user
    @Test
    @WithMockUser(roles = "OWNER")
    void getCurrentUser_Success() throws Exception {
        user.setId(1L);
        when(userService.getCurrentUser()).thenReturn(user);

        mockMvc.perform(get("/api/users/me"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.username").value("testuser"))
                .andExpect(jsonPath("$.id").value(1));
    }

    // 5️⃣ GET /api/users/role/{role} — ADMIN only
    @Test
    @WithMockUser(roles = "ADMIN")
    void getUsersByRole_Admin_Success() throws Exception {
        user.setId(1L);
        List<User> users = Arrays.asList(user);
        when(userService.getUsersByRole(Role.OWNER)).thenReturn(users);

        mockMvc.perform(get("/api/users/role/OWNER"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.size()").value(1))
                .andExpect(jsonPath("$[0].role").value("OWNER"))
                .andExpect(jsonPath("$[0].id").value(1));
    }

    @Test
    @WithMockUser(roles = "OWNER")
    void getUsersByRole_Owner_Forbidden() throws Exception {
        mockMvc.perform(get("/api/users/role/OWNER"))
                .andExpect(status().isForbidden());
    }

    // 6️⃣ GET /api/users/test — public test endpoint
    @Test
    void testEndpoint_Public_Success() throws Exception {
        mockMvc.perform(get("/api/users/test"))
                .andExpect(status().isOk())
                .andExpect(content().string("working"));
    }
}
