spring.application.name=TournamentManagerPro
# MySQL Connection Details
spring.datasource.url=jdbc:mysql://localhost:3306/tournamentdb
spring.datasource.username=root
spring.datasource.password=Harsh123#

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
