package com.harsh.tournamentmanagerpro.service;

import com.harsh.tournamentmanagerpro.entity.Role;
import com.harsh.tournamentmanagerpro.entity.User;
import com.harsh.tournamentmanagerpro.repository.UserRepository;
import com.harsh.tournamentmanagerpro.service.impl.UserServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class UserServiceImplTest {

    @Mock
    private UserRepository userRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private UserServiceImpl userService;

    private User user;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);

        // Mock SecurityContext for getCurrentUser() tests
        Authentication auth = mock(Authentication.class);
        when(auth.getName()).thenReturn("testuser");
        SecurityContext securityContext = mock(SecurityContext.class);
        when(securityContext.getAuthentication()).thenReturn(auth);
        SecurityContextHolder.setContext(securityContext);

        // Sample user
        user = new User();
        user.setUsername("testuser");
        user.setPassword("rawpassword");
        user.setRole(Role.OWNER);
    }

    @Test
    void testCreateUser_ShouldEncodePasswordAndSave() {
        when(passwordEncoder.encode("rawpassword")).thenReturn("encodedpassword");
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> {
            User u = invocation.getArgument(0);
            u.setId(1L); // Simulate autogenerated ID
            return u;
        });

        User saved = userService.createUser(user);

        assertEquals("encodedpassword", saved.getPassword());
        assertNotNull(saved.getId());
        verify(userRepository, times(1)).save(user);
        verify(passwordEncoder, times(1)).encode("rawpassword");
    }

    @Test
    void testGetAllUsers_ShouldReturnList() {
        user.setId(1L);
        when(userRepository.findAll()).thenReturn(Arrays.asList(user));

        List<User> users = userService.getAllUsers();

        assertEquals(1, users.size());
        assertEquals("testuser", users.get(0).getUsername());
    }

    @Test
    void testGetUserById_UserExists() {
        user.setId(1L);
        when(userRepository.findById(1L)).thenReturn(Optional.of(user));

        User found = userService.getUserById(1L);

        assertEquals("testuser", found.getUsername());
        assertEquals(1L, found.getId());
    }

    @Test
    void testGetUserById_UserNotFound_ShouldThrow() {
        when(userRepository.findById(99L)).thenReturn(Optional.empty());

        RuntimeException ex = assertThrows(RuntimeException.class, () -> userService.getUserById(99L));
        assertEquals("User not found with ID: 99", ex.getMessage());
    }

    @Test
    void testDeleteUser_UserExists() {
        when(userRepository.existsById(1L)).thenReturn(true);

        userService.deleteUser(1L);

        verify(userRepository, times(1)).deleteById(1L);
    }

    @Test
    void testDeleteUser_UserNotFound_ShouldThrow() {
        when(userRepository.existsById(99L)).thenReturn(false);

        RuntimeException ex = assertThrows(RuntimeException.class, () -> userService.deleteUser(99L));
        assertEquals("User not found with ID: 99", ex.getMessage());
    }

    @Test
    void testGetUsersByRole_ShouldReturnFilteredList() {
        user.setId(1L);
        when(userRepository.findByRole(Role.OWNER)).thenReturn(Arrays.asList(user));

        List<User> owners = userService.getUsersByRole(Role.OWNER);

        assertEquals(1, owners.size());
        assertEquals(Role.OWNER, owners.get(0).getRole());
    }

    @Test
    void testIsAdmin() {
        assertFalse(userService.isAdmin(user));

        user.setRole(Role.ADMIN);
        assertTrue(userService.isAdmin(user));
    }

    @Test
    void testGetCurrentUser_Found() {
        user.setId(1L);
        when(userRepository.findByUsername("testuser")).thenReturn(Optional.of(user));

        User current = userService.getCurrentUser();

        assertEquals("testuser", current.getUsername());
        assertEquals(1L, current.getId());
    }

    @Test
    void testGetCurrentUser_NotFound_ShouldThrow() {
        when(userRepository.findByUsername("testuser")).thenReturn(Optional.empty());

        RuntimeException ex = assertThrows(RuntimeException.class, () -> userService.getCurrentUser());
        assertEquals("Logged-in user not found: testuser", ex.getMessage());
    }
}
